import { useCallback, useEffect, useState } from "react";
import type { GraphData } from "../lib/types";
import { loadWikiData } from "../lib/layout";

export interface LoadProgress {
  receivedBytes: number;
  totalBytes: number | null;
}

interface UseGraphDataResult {
  data: GraphData | null;
  loading: boolean;
  error: string | null;
  progress: LoadProgress;
  fetchOverview: (
    project: string,
    maxNodes?: number,
    graph?: "code" | "missed",
  ) => void;
  fetchDetail: (project: string, centerNode: string) => void;
}

export const GRAPH_RENDER_NODE_LIMIT = 5000;
export const GRAPH_NODE_BUDGET_STEP = 5000;
export const GRAPH_NODE_BUDGET_MAX = 10_000_000;

export function clampNodeBudget(value: number): number {
  if (!Number.isFinite(value)) return GRAPH_RENDER_NODE_LIMIT;
  const stepped =
    Math.round(value / GRAPH_NODE_BUDGET_STEP) * GRAPH_NODE_BUDGET_STEP;
  if (stepped < GRAPH_NODE_BUDGET_STEP) return GRAPH_NODE_BUDGET_STEP;
  if (stepped > GRAPH_NODE_BUDGET_MAX) return GRAPH_NODE_BUDGET_MAX;
  return stepped;
}

export type GraphVariant = "code" | "missed";

const NO_PROGRESS: LoadProgress = { receivedBytes: 0, totalBytes: null };

/* Wiki fork: payload is graph-data.json generated by `wiki.py graph-data`
 * (layout computed client-side in lib/layout.ts — no backend). */
export function useGraphData(): UseGraphDataResult {
  const [data, setData] = useState<GraphData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchOverview = useCallback(() => {
    setLoading(true);
    setError(null);
    loadWikiData()
      .then((d) => {
        setData(d);
        setLoading(false);
      })
      .catch((e: Error) => {
        setError(e.message);
        setLoading(false);
      });
  }, []);

  return { data, loading, error, progress: NO_PROGRESS, fetchOverview, fetchDetail: fetchOverview };
}

/* Meta for App header / StatsTab without re-fetching. */
export function useWikiMeta() {
  const [meta, setMeta] = useState<GraphData["meta"] | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    loadWikiData()
      .then((d) => {
        setMeta(d.meta ?? null);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);
  return { meta, loading };
}
