"""Derived views: deterministic page builders + verification gates.

Concept/procedure prose is written by the agent for invalidated pages only;
index/decision/changes stubs are built here. Every derived page carries
yamlite frontmatter with its dependency set (PRD §17). Derived state is
disposable — deleting wiki/ and re-running build_pages restores it (PRD §8.2).
"""
import calendar
import json
import os
import re
import time

from . import claims, deps, ids, review, synthesize
from .transaction import Transaction, TxnError
from .yamlite import dumps as yamldumps, loads as yamlloads

LINK_RE = re.compile(r"\[\[([a-z]+_[0-9A-Za-z]+)\]\]")


def _now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _page(rel: str, front: dict, body: str) -> str:
    return "---\n%s\n---\n\n%s" % (yamldumps(front), body.strip() + "\n")


def _front(text: str) -> dict:
    """Parse a page's fenced frontmatter block (yamlite needs closing --- at end)."""
    if not text.startswith("---\n"):
        return {}
    parts = text.split("---\n", 2)
    if len(parts) < 3:
        return {}
    return yamlloads("---\n" + parts[1] + "\n---\n")


def _page_title(path: str) -> str:
    """One-line title for a derived page: frontmatter title, then first body heading."""
    try:
        with open(path, encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return "-"
    title = str(_front(text).get("title") or "").strip()
    if title:
        return title
    for line in text.split("---", 2)[-1].splitlines():
        line = line.strip()
        if line.startswith("# "):
            return line[2:].strip()
    return "-"


def _section_files(wiki, sub: str) -> list:
    """Non-index .md filenames in wiki/<sub>, sorted."""
    subdir = wiki.p("wiki", sub)
    if not os.path.isdir(subdir):
        return []
    return [n for n in sorted(os.listdir(subdir)) if n.endswith(".md") and n != "index.md"]


def _age_days(ts) -> int:
    return review.age_days(ts)


def _subject_pages(wiki) -> dict:
    """subject -> artifact rel path, from page frontmatter declarations."""
    out = {}
    for sub in synthesize.PAGE_KINDS:
        for name in _section_files(wiki, sub):
            rel = "wiki/%s/%s" % (sub, name)
            try:
                with open(wiki.p(rel), encoding="utf-8") as f:
                    subj = _front(f.read()).get("subject")
            except OSError:
                continue
            if subj and subj not in out:
                out[subj] = rel
    return out


def _affected_links(affected, known_ids) -> str:
    parts = [("[[%s]]" % a if a in known_ids else str(a)) for a in affected or []]
    return ", ".join(parts) or "-"


def _review_queue_lines(wiki, known_ids, intro: str) -> list:
    """'## Review queue' body: open/deferred counts + per-item rows (R1)."""
    items = [i for i in wiki.read_jsonl(review.QUEUE)
             if i.get("status") in ("open", "deferred")]
    items.sort(key=lambda i: (i.get("created_at") or "", i.get("id") or ""))
    s = review.summary(wiki)
    lines = [intro % (s["open"], s["deferred"], s["total"]), ""]
    if not items:
        return lines + ["No open or deferred review items."]
    lines += ["| Item | Kind | Status | Risk | Age (d) | Affected | Problem |",
              "|---|---|---|---|---|---|---|"]
    for it in items:
        lines.append("| %s | %s | %s | %s | %d | %s | %s |" % (
            it.get("id", "-"), it.get("kind", "-"), it.get("status", "-"),
            it.get("risk", "-"), _age_days(it.get("created_at")),
            _affected_links(it.get("affected"), known_ids),
            str(it.get("problem") or "-").replace("|", "\\|")))
    return lines


def write_changes_index(wiki) -> str:
    """Deterministic `wiki/changes/index.md` from .state/operations.jsonl (R3).

    Script-owned: regenerated by build_pages, never agent-authored.
    """
    recs = []
    path = wiki.p(".state/operations.jsonl")
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    recs.append(json.loads(line))
                except ValueError:
                    continue
    lines = ["# Changes", "",
             "Operational log derived from `.state/operations.jsonl`. "
             "Script-owned — do not edit.", "",
             "| Revision | At | Op | Run | Affected |",
             "|---|---|---|---|---|"]
    for rec in recs:
        rev = rec.get("revision") or {}
        affected = ", ".join(
            "%s=%s" % (k, ",".join(str(v) for v in val) if isinstance(val, list) else val)
            for k, val in sorted((rec.get("changes") or {}).items())) or "-"
        lines.append("| %s->%s | %s | %s | %s | %s |" % (
            rev.get("before", "-"), rev.get("after", "-"),
            rec.get("finished_at", "-"), rec.get("command", "-"),
            rec.get("run_id", "-"), affected))
    front = {"type": "index", "section": "changes", "generated": _now(), "deps": []}
    return _page("wiki/changes/index.md", front, "\n".join(lines))



def _coverage_gaps(wiki) -> list:
    """Source ids whose extraction left text unextracted (R8 coverage gaps)."""
    gaps = []
    sdir = wiki.p("sources")
    if not os.path.isdir(sdir):
        return gaps
    for sid in sorted(os.listdir(sdir)):
        xpath = wiki.p("sources", sid, "extraction.json")
        if not os.path.isfile(xpath):
            continue
        try:
            with open(xpath, encoding="utf-8") as f:
                cov = (json.load(f).get("extraction_report") or {}).get("coverage", {})
        except (ValueError, OSError):
            continue
        if cov.get("text") == "not_extracted":
            gaps.append(sid)
    return gaps


def build_pages(wiki, base_revision: int) -> dict:
    """(Re)build deterministic views and register their dependency sets."""
    txn = Transaction(wiki, "wiki-build-pages")
    built = []

    all_claims = claims.list_claims(wiki)
    decisions = claims.list_decisions(wiki)
    claim_versions = {c["id"]: c["version"] for c in all_claims}
    section_files = {sub: _section_files(wiki, sub) for sub in synthesize.PAGE_KINDS}

    # --- index.md (reviewer inventory, R6) --------------------------------
    known_ids = {c["id"]: c["version"] for c in all_claims}
    known_ids.update({d["id"]: d["version"] for d in decisions})
    claim_subject = {c["id"]: c["subject"] for c in all_claims}
    open_rev = {}
    for it in wiki.read_jsonl(review.QUEUE):
        if it.get("status") != "open":
            continue
        for aid in it.get("affected") or []:
            subj = claim_subject.get(aid)
            if subj:
                open_rev[subj] = open_rev.get(subj, 0) + 1
                break
    subject_pages = _subject_pages(wiki)
    stale_set = set(deps.stale_artifacts(wiki))

    by_subject = {}
    for c in all_claims:
        by_subject.setdefault(c["subject"], []).append(c)
    live_order = ("candidate", "provisional", "accepted", "disputed")
    lines = ["# Wiki index", ""]
    top_links = ["[Overview](overview.md)", "[Review queue](review.md)"]
    top_links += ["[%s](%s/index.md) (%d)" % (sub, sub, len(section_files[sub]))
                  for sub in synthesize.PAGE_KINDS if section_files[sub]]
    lines.append(" | ".join(top_links))
    lines += ["",
              "| Subject | Live statuses | Disputed | Open reviews | Sources "
              "| Last changed | Stale | Page |",
              "|---|---|---|---|---|---|---|---|"]
    for subject in sorted(by_subject):
        cs = by_subject[subject]
        counts = {}
        for c in cs:
            if c["status"] not in claims.TERMINAL:
                counts[c["status"]] = counts.get(c["status"], 0) + 1
        live_cell = ", ".join("%s %d" % (st, counts[st])
                              for st in live_order if counts.get(st)) or "-"
        disputed = sum(1 for c in cs if c["status"] == "disputed")
        srcs = len({ev.get("source_id") for c in cs
                    for ev in c.get("evidence", [])} - {None})
        last = max((c.get("updated_at") or c.get("recorded_at") or "")
                   for c in cs)[:10] or "-"
        page = subject_pages.get(subject)
        stale_cell = "yes" if page and page in stale_set else "-"
        mark = " [DISPUTED]" if disputed else (" [SUPERSEDED]" if not counts else "")
        link = page[len("wiki/"):] if page else None
        lines.append("| %s%s | %s | %d | %d | %d | %s | %s | %s |" % (
            subject, mark, live_cell, disputed, open_rev.get(subject, 0),
            srcs, last, stale_cell,
            ("[%s](%s)" % (link, link) if link else "-")))
    front = {"type": "index", "generated": _now(), "deps": []}
    txn.stage_write("wiki/index.md", _page("wiki/index.md", front, "\n".join(lines)))
    built.append("wiki/index.md")
    deps.register(txn, "wiki/index.md", [])


    # --- review.md (queue page, R1) ---------------------------------------
    rel = "wiki/review.md"
    body = ["# Review queue", ""] + _review_queue_lines(
        wiki, known_ids, "%d open, %d deferred, %d total.")
    front = {"type": "review", "generated": _now(), "deps": []}
    txn.stage_write(rel, _page(rel, front, "\n".join(body)))
    built.append(rel)
    deps.register(txn, rel, [])

    # --- changes/index.md (R3, script-owned ops log) -----------------------
    rel = "wiki/changes/index.md"
    txn.stage_write(rel, write_changes_index(wiki))
    built.append(rel)
    deps.register(txn, rel, [])
    # --- decision pages ---------------------------------------------------
    for d in decisions:
        deps_list = ["%s@%d" % (d["id"], d["version"])]
        rows = ["| Subject | Predicate | Value | Scope | Status |", "|---|---|---|---|---|"]
        for cid in d.get("claims", []):
            try:
                c = claims.load_claim(wiki, cid)
            except TxnError:
                continue
            deps_list.append("%s@%d" % (c["id"], c["version"]))
            scope = ", ".join("%s=%s" % kv for kv in sorted((c.get("scope") or {}).items())) or "-"
            rows.append("| %s | %s | %s | %s | %s |" % (
                c["subject"], c["predicate"], c.get("value"), scope, c["status"]))
        body = ["# %s" % d["title"], "", "Status: **%s**" % d["status"], ""]
        if d.get("body"):
            body += [d["body"], ""]
        body += ["## Supporting claims", ""] + rows
        rel = "wiki/decisions/%s.md" % d["id"]
        front = {"type": "decision", "decision": d["id"], "generated": _now(), "deps": deps_list}
        txn.stage_write(rel, _page(rel, front, "\n".join(body)))
        built.append(rel)
        deps.register(txn, rel, deps_list)

    # --- section indexes (progressive disclosure) -------------------------
    for sub in synthesize.PAGE_KINDS:
        if sub == "changes":
            continue  # wiki/changes/index.md is owned by write_changes_index
        rel = "wiki/%s/index.md" % sub
        names = section_files[sub]
        if not names:
            if os.path.isfile(wiki.p(rel)):
                txn.stage_delete(rel)

                def _drop(data, _rel=rel):
                    data.setdefault("edges", {}).pop(_rel, None)
                    data["stale"] = [a for a in data.get("stale", []) if a != _rel]

                txn.stage_state(deps.DEPS_FILE, _drop)
            continue
        rows = ["| Page | Title |", "|---|---|"]
        for name in names:
            rows.append("| [%s](%s) | %s |"
                        % (name[:-3], name, _page_title(wiki.p("wiki", sub, name))))
        front = {"type": "index", "section": sub, "generated": _now(), "deps": []}
        txn.stage_write(rel, _page(rel, front, "\n".join(rows)))
        built.append(rel)
        deps.register(txn, rel, [])

    # --- overview.md ------------------------------------------------------
    overview = ["# Overview", "", "| Section | Pages |", "|---|---|"]
    for sub in synthesize.PAGE_KINDS:
        overview.append("| [%s](%s/index.md) | %d |" % (sub, sub, len(section_files[sub])))
    overview.append("| decisions | %d |" % len(decisions))
    overview += ["", "## Section indexes", ""]
    section_links = ["- [%s](%s/index.md) (%d)" % (sub, sub, len(section_files[sub]))
                     for sub in synthesize.PAGE_KINDS if section_files[sub]]
    overview += section_links if section_links else ["- (no sections yet)"]
    # R8: review queue, stale pages, disputed/superseded, orphans, coverage,
    # synthesis targets — each with actionable ids/links.
    overview += ["", "## Review queue", ""] + _review_queue_lines(
        wiki, known_ids,
        "%d open, %d deferred, %d total — full table: [review.md](review.md).")
    overview += ["", "## Stale pages", ""]
    stale = sorted(stale_set)
    if stale:
        overview += ["- [%s](%s) — rebuild via build-pages" % (a[len("wiki/"):], a[len("wiki/"):])
                     for a in stale if a.startswith("wiki/")]
        overview += ["- %s (non-wiki artifact)" % a for a in stale if not a.startswith("wiki/")]
    else:
        overview.append("No stale artifacts.")
    disputed = sorted((c for c in all_claims if c["status"] == "disputed"),
                      key=lambda c: c["id"])
    overview += ["", "## Disputed claims", ""] + (
        ["| Claim | Subject |", "|---|---|"]
        + ["| [[%s]] | %s |" % (c["id"], c["subject"]) for c in disputed]
        if disputed else ["None."])
    superseded = sorted((c for c in all_claims if c["status"] == "superseded"),
                        key=lambda c: c["id"])
    overview += ["", "## Superseded claims", ""] + (
        ["| Claim | Supersedes | Superseded by |", "|---|---|---|"]
        + ["| [[%s]] | %s | %s |" % (c["id"],
                                     ", ".join(c.get("supersedes") or []) or "-",
                                     c.get("superseded_by") or "-")
           for c in superseded]
        if superseded else ["None."])
    orphans = sorted((c for c in all_claims if not c.get("evidence")),
                     key=lambda c: c["id"])
    overview += ["", "## Orphan claims", ""] + (
        ["| Claim | Subject |", "|---|---|"]
        + ["| [[%s]] | %s |" % (c["id"], c["subject"]) for c in orphans]
        if orphans else ["None."])
    gaps = _coverage_gaps(wiki)
    overview += ["", "## Coverage gaps", ""] + (
        ["- `%s` — text not extracted; re-ingest with a document parser" % s
         for s in gaps] if gaps else ["None."])
    targets = synthesize.page_targets(wiki)
    ready = targets.get("targets") or []
    waiting = targets.get("waiting") or []
    overview += ["", "## Synthesis targets", ""]
    if ready or waiting:
        overview += ["| Subject | Kind | Claims | Origins | Artifact | Status |",
                     "|---|---|---|---|---|---|"]
        for t in ready:
            link = t["artifact"][len("wiki/"):]
            status = ("stale — rebuild" if t["stale"]
                      else ("exists" if t["exists"] else "not written"))
            overview.append("| %s | %s | %d | %d | [%s](%s) | %s |" % (
                t["subject"], t["kind"], t["claim_count"],
                t["distinct_origins"], link, link, status))
        for w in waiting:
            overview.append("| %s | - | %d | %d | - | below threshold |" % (
                w.get("subject", "-"), w.get("claim_count", 0),
                w.get("distinct_origins", 0)))
    else:
        overview.append("No synthesis targets.")
    front = {"type": "overview", "generated": _now(), "deps": []}
    txn.stage_write("wiki/overview.md", _page("wiki/overview.md", front, "\n".join(overview)))
    built.append("wiki/overview.md")
    deps.register(txn, "wiki/overview.md", [])

    # agent-authored pages: mark stale in place, PRESERVING the prose body —
    # regeneration is the agent's job; deterministic builds never clobber it
    for sub in ("concepts", "entities", "procedures", "questions"):
        subdir = wiki.p("wiki", sub)
        if not os.path.isdir(subdir):
            continue
        for name in sorted(os.listdir(subdir)):
            if not name.endswith(".md") or name == "index.md":
                continue
            rel = "wiki/%s/%s" % (sub, name)
            if deps.is_stale(wiki, rel):
                with open(os.path.join(subdir, name)) as f:
                    text = f.read()
                front = _front(text)
                front["stale"] = True
                txn.stage_write(rel, _page(rel, front, text.split("---", 2)[-1]))

    txn.changes = {"pages_built": len(built)}
    receipt = txn.commit(base_revision)

    # clear stale flags for artifacts we just rebuilt
    cleared = [a for a in deps.stale_artifacts(wiki) if a in built]
    if cleared:
        txn2 = Transaction(wiki, "wiki-build-pages-clear")
        deps.clear_stale(txn2, cleared)
        txn2.commit(wiki.revision())
    receipt["changes"]["pages_built"] = len(built)
    return receipt


def verify(wiki) -> dict:
    """Citation + staleness gates (PRD §58: every citation resolves; stale
    derived artifacts must not silently remain current)."""
    errors = []
    g = deps.graph(wiki)
    edges = g.get("edges", {})
    stale = set(g.get("stale", []))

    known_ids = {c["id"]: c["version"] for c in claims.list_claims(wiki)}
    known_ids.update({d["id"]: d["version"] for d in claims.list_decisions(wiki)})

    for artifact, dep_list in edges.items():
        path = wiki.p(artifact)
        if not os.path.isfile(path):
            errors.append("missing artifact: %s" % artifact)
            continue
        if artifact in stale:
            errors.append("stale artifact not rebuilt: %s" % artifact)
        if artifact == "wiki/index.md":
            continue
        with open(path) as f:
            text = f.read()
        if not text.startswith("---\n"):
            errors.append("missing frontmatter: %s" % artifact)
            continue
        front = _front(text)
        for dep in front.get("deps", []) or []:
            err = _check_dep(wiki, dep, artifact, known_ids, edges)
            if err:
                errors.append(err)
        for target in LINK_RE.findall(text.split("---", 2)[-1]):
            if target not in known_ids:
                errors.append("unresolved wiki-link [[%s]] in %s" % (target, artifact))

    # every derived page must be registered with a dependency set (PRD §17)
    for sub in ("sources", "concepts", "entities", "procedures", "questions",
                "decisions", "changes"):
        subdir = wiki.p("wiki", sub)
        if not os.path.isdir(subdir):
            continue
        for name in sorted(os.listdir(subdir)):
            if not name.endswith(".md"):
                continue
            rel = "wiki/%s/%s" % (sub, name)
            if rel not in edges:
                errors.append("derived page missing dependency registration: %s" % rel)

    return {"ok": not errors, "errors": errors, "stale": sorted(stale)}


def _check_dep(wiki, dep, artifact, known_ids, edges):
    """Typed dep resolution (contract): `claim_X@N` / `decision_Y@N` must
    match the current version; `wiki/<dir>/<slug>.md` must be a registered
    edge or an existing file. Returns an error string or None."""
    dep = str(dep).strip()
    dep_id, _, ver = dep.partition("@")
    if dep_id.startswith("wiki/"):
        if dep_id in edges or os.path.isfile(wiki.p(dep_id)):
            return None
        return "unresolved dependency %r in %s" % (dep, artifact)
    if dep_id.startswith("review_"):
        queue_ids = {i.get("id") for i in wiki.read_jsonl(review.QUEUE)}
        if dep_id in queue_ids:
            return None
        return "unresolved dependency %r in %s" % (dep, artifact)
    cur = known_ids.get(dep_id)
    if ver and (not ver.isdigit() or int(ver) != cur):
        return ("dependency %s@%s in %s does not match current version %d"
                % (dep_id, ver, artifact, cur))
    return None
